### ISSUE TITLE
How to reduce the model size?

### ISSUE THREAD

**Issue by wincle** [antoine77340/Youtube-8M-WILLOW#11]
The trained model size is over 1 GB, How could I reduce the model size?

**Comment by antoine77340** [comment]
The best way to reduce the model size is to  change:
- Number of clusters in NetVLAD, typically 64 should be enough to get good scores.
- You can remove Context Gating after probability. It won't change the results much. You have to set
 --moe_prob_gating=False.

If you do this it should be much lighter than the best Gated NetVLAD. The performance will just be slightly worse but you won't notice a difference I guess.

**Comment by wincle** [comment]
Thank you so much !

**Comment by speculaas** [comment]
Dear Antoine, 
According to README: some of the models do not fit with a GPU with less than 9GB of memory.
Can you tell us which models don't fit into 9GB-ram-gpu?
BR,
JimmyYS

**Comment by antoine77340** [comment]
I think maybe NetVLAD and NetFV but not sure at all since I do not own a 9GB GPU.

**Comment by speculaas** [comment]
Dear Antoine, 
Thanks for your help and rapid response!
Is "Gated NetVLAD" different from "NetVLAD"?
I hope they are different. 
Since I don't have a 9GB GPU either.

I am surveying video classification, and want to do some initial trials.

I came across : 
https://github.com/wangheda/youtube-8m
https://github.com/jeffreyhuang1/two-stream-action-recognition
https://github.com/harvitronix/five-video-classification-methods
And they all are without pretrained model. 

So far, I have read Andrej Karpathy's large scale video classification with conv neural network.
I think Andrej's paper mentioned several interesting ideas, for example convolving also temporal dimension.

But, unfortunately, their source code is not open source.

BR,
JimmyYS

**Comment by antoine77340** [comment]
Yes I also meant Gated NetVLAD, but I'm sure it can fit into a 9gb GPU if you only set the number of clusters to 128 and not 256.
